##############################################################
# Authentication and IAM Outputs
##############################################################

## Account Roles Module Outputs

output "account_role_prefix" {
  value       = var.create_account_roles ? module.account_iam_resources[0].account_role_prefix : null
  description = "The prefix used for all generated AWS resources."
}

output "account_roles_arn" {
  value       = var.create_account_roles ? module.account_iam_resources[0].account_roles_arn : null
  description = "A map of Amazon Resource Names (ARNs) associated with the AWS IAM roles created. The key in the map represents the name of an AWS IAM role, while the corresponding value represents the associated Amazon Resource Name (ARN) of that role."
}

output "path" {
  value       = var.create_account_roles ? module.account_iam_resources[0].path : null
  description = "The arn path for the account/operator roles as well as their policies."
}

## OIDC Config and Provider Module Outputs

output "oidc_config_id" {
  value       = var.create_oidc ? module.oidc_config_and_provider[0].oidc_config_id : null
  description = "The unique identifier associated with users authenticated through OpenID Connect (OIDC) generated by this OIDC config."
}

output "oidc_endpoint_url" {
  value       = var.create_oidc ? module.oidc_config_and_provider[0].oidc_endpoint_url : null
  description = "Registered OIDC configuration issuer URL, generated by this OIDC config."
}

## Operator Roles Module Outputs

output "operator_role_prefix" {
  value       = var.create_operator_roles ? module.operator_roles[0].operator_role_prefix : null
  description = "Prefix used for generated AWS operator policies."
}

output "operator_roles_arn" {
  value       = var.create_operator_roles ? module.operator_roles[0].operator_roles_arn : null
  description = "List of Amazon Resource Names (ARNs) for all operator roles created."
}

##############################################################
# OCM Role Output
##############################################################

output "ocm_role_arn" {
  value       = var.create_ocm_role ? aws_iam_role.ocm_role[0].arn : null
  description = "ARN of the OCM (OpenShift Cluster Manager) role"
}

##############################################################
# RHCS Authentication Outputs
##############################################################

output "rhcs_url" {
  description = "Red Hat OpenShift Cluster Manager URL being used"
  value       = var.rhcs_url
}

output "rhcs_authentication_method" {
  description = "RHCS authentication method being used"
  value       = var.rhcs_token != null ? "token" : (var.rhcs_client_id != null ? "client_credentials" : "environment_variables")
}##############################################################
# Cluster Information Outputs
##############################################################

output "cluster_id" {
  value       = module.rosa_cluster_hcp.cluster_id
  description = "Unique identifier of the cluster."
}

output "cluster_admin_username" {
  value       = module.rosa_cluster_hcp.cluster_admin_username
  description = "The username of the admin user."
}

output "cluster_admin_password" {
  value       = module.rosa_cluster_hcp.cluster_admin_password
  description = "The password of the admin user."
  sensitive   = true
}

output "cluster_api_url" {
  value       = module.rosa_cluster_hcp.cluster_api_url
  description = "The URL of the API server."
}

output "cluster_console_url" {
  value       = module.rosa_cluster_hcp.cluster_console_url
  description = "The URL of the console."
}

output "cluster_domain" {
  value       = module.rosa_cluster_hcp.cluster_domain
  description = "The DNS domain of cluster."
}

output "cluster_current_version" {
  value       = module.rosa_cluster_hcp.cluster_current_version
  description = "The currently running version of OpenShift on the cluster, for example '4.11.0'."
}

output "cluster_state" {
  value       = module.rosa_cluster_hcp.cluster_state
  description = "The state of the cluster."
}

##############################################################
# Machine Pools Outputs
##############################################################

output "additional_machine_pools" {
  value = {
    for k, v in module.rhcs_hcp_machine_pool : k => {
      id        = v.machine_pool_id
      name      = v.machine_pool_name
      subnet_id = v.subnet_id
      replicas  = v.replicas
    }
  }
  description = "Map of additional machine pools created"
}##############################################################
# OpenShift Features and Operators Outputs
##############################################################

## OpenShift GitOps Outputs

output "openshift_gitops_enabled" {
  description = "Whether OpenShift GitOps operator is deployed"
  value       = var.deploy_openshift_gitops
}

output "vote_application_enabled" {
  description = "Whether vote application is deployed via ArgoCD"
  value       = var.deploy_vote_application && var.deploy_openshift_gitops
}

output "gitops_repo_url" {
  description = "GitOps repository URL configured for ArgoCD"
  value       = var.deploy_vote_application && var.deploy_openshift_gitops ? var.gitops_repo_url : null
}

output "argocd_server_url" {
  description = "ArgoCD server URL (available when vote application is deployed)"
  value       = var.deploy_vote_application && var.deploy_openshift_gitops ? "https://openshift-gitops-server-openshift-gitops.apps.${module.rosa_cluster_hcp.cluster_domain}" : null
}

## Operator Deployment Outputs

output "openshift_ai_enabled" {
  description = "Whether OpenShift AI operator is deployed via ArgoCD"
  value       = var.deploy_openshift_ai && var.deploy_openshift_gitops
}

output "openshift_serverless_enabled" {
  description = "Whether OpenShift Serverless operator is deployed via ArgoCD"
  value       = local.deploy_openshift_serverless && var.deploy_openshift_gitops
}

output "openshift_servicemesh_enabled" {
  description = "Whether OpenShift Service Mesh operator is deployed via ArgoCD"
  value       = local.deploy_openshift_servicemesh && var.deploy_openshift_gitops
}

output "nfd_gitops_enabled" {
  description = "Whether NodeFileDiscovery operator is deployed via ArgoCD using GitOps catalog"
  value       = local.deploy_nfd && var.deploy_openshift_gitops
}

output "nvidia_gpu_operator_gitops_enabled" {
  description = "Whether NVIDIA GPU operator is deployed via ArgoCD using GitOps catalog"
  value       = local.deploy_nvidia_gpu_operator && var.deploy_openshift_gitops
}

output "openshift_lightspeed_enabled" {
  description = "Whether OpenShift Lightspeed operator is deployed via ArgoCD using GitOps catalog"
  value       = local.deploy_openshift_lightspeed && var.deploy_openshift_gitops
}

output "authorino_operator_enabled" {
  description = "Whether Authorino operator is deployed via ArgoCD using GitOps catalog"
  value       = var.deploy_authorino_operator && var.deploy_openshift_gitops
}

output "ai_model_enabled" {
  description = "Whether AI model is deployed via ArgoCD"
  value       = var.deploy_ai_model && var.deploy_openshift_gitops
}

output "openshift_ai_application_enabled" {
  description = "Whether OpenShift AI operator application is deployed via ArgoCD"
  value       = var.deploy_openshift_ai && var.deploy_openshift_gitops
}##############################################################
# VPC and Network Outputs
##############################################################

output "vpc_id" {
  value       = var.create_vpc ? module.vpc[0].vpc_id : null
  description = "ID of the VPC created by the VPC module"
}

output "vpc_cidr" {
  value       = var.create_vpc ? module.vpc[0].cidr_block : null
  description = "CIDR block of the VPC created by the VPC module"
}

output "private_subnets" {
  value       = var.create_vpc ? module.vpc[0].private_subnets : var.aws_subnet_ids
  description = "List of private subnet IDs used by the cluster"
}

output "cluster_subnets" {
  value       = local.cluster_subnet_ids
  description = "List of all subnet IDs (public + private) used by the cluster"
}

output "public_subnets" {
  value       = var.create_vpc ? module.vpc[0].public_subnets : null
  description = "List of public subnet IDs created by the VPC module (only available when create_vpc is true)"
}

output "availability_zones" {
  value       = var.create_vpc ? module.vpc[0].availability_zones : var.aws_availability_zones
  description = "List of availability zones used by the VPC/cluster"
}