apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-hub-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-devspaces-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-ai-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-model
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
